In [1]:
import numpy as np

## Придумайте матрицы, которые обладают следующими свойствами:
####  a) Диагональная, ортогональная, но не единичная(!)

In [80]:
A = np.array([[1, 0],[0, -1]])
print(A)

[[ 1  0]
 [ 0 -1]]


In [83]:
A.dot(A.T)

array([[1, 0],
       [0, 1]])

#### b) Верхнетреугольная, ортогональная

#### c) Нижнетреугольная, ортогональная

Не понимаю как матрицы этих типов могут быть ортогональны, если пусть A = np.array([[a, b], [c, d]]), то есть a*c + b*d = 0. В задаче b) с = 0, а в задаче с) b = 0. То есть у нас в обоих примерах должен получиться ноль при перемножении двух чисел, оба из которых нулями не являются. Но это же невозможн?!

#### d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [67]:
D = np.array([[5, 7],[2, 3]])
print(D)

[[5 7]
 [2 3]]


In [69]:
d = np.linalg.det(D)
print(d)
# теоретически 15 - 14 = 1 :))))))

0.9999999999999991


#### Найдите собственные значения и собственные вектора матриц:

In [71]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [73]:
w,v = np.linalg.eig(m)

In [74]:
# Собственные числа матрицы m
w

array([1., 4.])

In [76]:
# Собственные векторы матрицы m
v

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])