### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [6]:
import numpy as np

In [7]:
def array_creation(n):
    return np.arange(n-1, -1, -1)
print(array_creation(10))

[9 8 7 6 5 4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [20]:
def matrix_creation(n):
    print (np.diag(np.arange(n, -1, -1)))
    print(f"Сумма значение по диагонали: {np.arange(n, -1, -1).sum()}")

matrix_creation(3)

[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]]
Сумма значение по диагонали: 6


## Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [23]:
from numpy import linalg

In [24]:
a = np.array([[4, 1, 5],[2, 3, 0],[1, 0, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 1.8,  2.8, -1.2])

### Задание 4

In [25]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [26]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [29]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [61]:
check = cosine(next_user_stats,users_stats[0])
user_id = 1
for num,i in enumerate(users_stats, 1):
    k = cosine(i, next_user_stats)
    if k > check:
        check = k
        user_id = num
print(f"Самый похожий пользователь user_ID={user_id} со значением косинуса {check:5f}")

Самый похожий пользователь user_ID=8 со значением косинуса 0.948683
